{{ with .Values.applications.influxdata }}
{{ if and .enabled .ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .ingress.name }}
  namespace: {{ .namespace }}
  labels:
    app: {{ .ingress.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ printf "%s.%s" "influxdb" (include "helm.personalDomain" $)}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: influxdb-influxdb2
            port:
              name: http
  tls:
  - hosts:
    - {{ printf "%s.%s" "influxdb" (include "helm.personalDomain" $)}}
    secretName: {{ printf "%s-tls" .ingress.name }}
{{- end -}}
{{- end -}}