apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: private-repo-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBszA3Y2dwU93F7OPjr8AU+5NF23Q98QEly7OItK6DJwUtIZXTBJOa86KCWZNQaRCPzV7p+WDfAO4pf4coEv7T91Wv/0iCgToZWwN2CfJBdreRkFzYZCXG/6ACsKAD7iWdjM8vsXDRAj6Rjb5Ant3ck+zCioezx4m5dqHfeYpDPtcfYm27FcHLT7iaOtYJQAIvLn3w2MP9YjCHEI72ENGeNXVsWM1YDr8ZVlF+dPOJrYUGQ5hTIyB5cOguOqTs0yYYfYmvMjd9pyxAnZoU8c7SSQyZng+aI8xkAyBIOH91sWQou1AQCzMGa+lWFZ6TKxO43pCZKQikBGYQ1i4+8vXv58UhOR6rsCAeoL6xnGIvifVupY22U7jg1Ytujg2JEv2pvpM3FHtiksQIaC522HnPwXjgTjnCbjkuS7pZaCsfo2bHk20lVBhIl9+WL1j1VZCyi5cvE0VviPpijx182jmJIGJjCkmxZAvosUzIzFGhvxHSMJubWM0pXHqvCBok/rHkoDrSWDyWKn0hkqEX0s3bnuxvDcWmq3LtoXoQo1bZqDBGigz5S+OQxD/4Wn9kHH/39E1NkVzMjm8N1Ab3N11R1nZMvMh74PBBRuDj5xXmHXlSoTak05RjMTNnnlLGhb/o3tG/cgjIGl99JPpLrI/OM4IEWhRbF/nbcFpQmcMx7BXoikwyEuotvBl6fCbgmsxJUBAnTmMyyRe78SZala5OyjNWnCtf/Yt4oASUilC6s5yBTEIUg9IuY
    type: AgBcH3eGr2aP6VEMRy1AMHJFuTYfLPv27zuZa9xB3clHGrJXEX16X9SvBLh9FB5yVe8KrlfT4ddN3efTjTgyXbMhwSht4WyeWUe0kZCccF2qveYYuQTK/FufEBfYyswaorQP6Hx+V5Qzco054DqSDYcP8NjxI7xkxZU1sJvxwYEUVjVb8bDikpXTWw8yx1AubByx/FfRSsNjYC2aNb238TEC1Iq7Wlj1C5xqvhyBQ693lH2+2QZqQaRWaU58hd31MmeP1NIDVK3UKnTPQ/K5BpAJThhJkcADZJnuzyN/9YQGoP1vVSXvbOAtHMLgv3pQAECk6N4eFA+zLnUok9Akpybqchftk/uIokP81ogjTownCn3eIkWl2EO4NnC2kssugZhTwxF7RONokSqmRlskjpC2hVKe0NaCFac44knZhV34fPjs02FGFmxqOpkouifuHvn85UD+IsRWF3Gk0a92iVQuxsTDYL1rXMGahjHeePJRGKvIpAud+G8vhp2VFWsOTOKVKxKFTJr3CWXx3hs4ZI+llu5VtABwvcnBrwvyo2g/c6YDGlYY1uup8WPFtfCDAjlAPf/sbqn0ozXfC8efjfgL8QJntzAfnOs+ScWG8610OnChybH6E6ZXam9AYnv5vvDUcqzVPjKVBjFRFIH2Jwh5kBZDkIdj0ffuhMcyzaQuqmi3RmkR2YSBGtuuU7zEB93qZKI=
    url: AgBjpsmlwFfdtfXIKJPSMfVSo9zgmZN1ATNBSzMLLDOVZZW/CCeqmER2Mj2YcGawR/VGGaoU32Fvt6z4YBkvVdSTeafMV1kpqNYF3trLB+XWIJziPOvwvPE6SQifFd4yMyUP7dQ0X10IDSEPmQ9buv6w9UvMplc6tRUww6az3doGSofKK1WxlGTnT8zHgTHcuM1bYePE1DzV/Z0fiElh+L5sqQPyhUZKFoguPDBD0IsUEyQPIZvgwP605lSQ28aHl+MXK5taA1qbLJ0GnuPRB2JTXi+HeUW52P/Jy7B9fZcGI1UlXw/Ulidw+qR+EEotK7MQzZFiF/L6h7PtR9MJU26CmOTxgtXvb2poYgIhYMdyVzKkKsLgnCyKYHydaDJMOiqpff/1JnQ/b98IEacm2DqOMgmXLkQJEnLloZO5/LVVJRye9NzqfGqOCQ9a4M2aC7NELtO6OYu8D5eiJtE/ALnrFe7lVPg1MQQXr01kUC6ljKfdJle6Q4GQwm6UqNfTScZdrVZo+VNhf10tYQ1OiUZZKaGG86Hp6s2t7bjWbicCJ4HjT82+32jvnv1HGW5+q859HTgsKkPYXeBkylB4T7iyCUKbw3mnUtwtgBz4xhgQ1thO+o0qWvryifqrw9Qq8WovUeekI7xHjAgzfYKlthuSZU/Idx09waMRMEcoyNiikeeREabn7pHVXQ0E7bDHv9lcCGOepTVGI3ny+PwuDzHLgzNXF2Vr+eIzw4mF
    username: AgC9abg47u91GfZZBhMR6d5y1K9iJGdOooE5LYdRv8XnorAssChtq3oM3o98EFrv/mgnyLHbxVhXU7NU5KwjqxSBrVwO3iZ7wbJF4SUabcfblV9IAhQQr64bVIG7vH5c1BFKxjM2699ePt6Lg1yBR2GVQ8wpktObQYC11c5g0yVR7uUSoSAv3RpxxI8xOrBzfRHFTLgx4VncGnVCHxI6/xjp2LzDRrxg7zIiziBmCwh9klHu9r3nPNJteXOtQ8G/UjT6HkwTLBDdUCXRZ4/QWS43ZbbJcd7VcmsDehaN06lsbO1R5SEYID+FzML0tVa6uoUKHcACGZg2laS2H7JdGaI2wZXdtiQY3yWC+EbeKP5K1HYB6qfOeeuhqlyWbkLyc9khLeGKTEi0oYPxzd7/S2NM4kA19SqjZCRJ5UIc/sF62Foh7HeU9tAp1LN95/kQVTP/jm0Qn9phbANOSoe0sFVOY6+Zi/dG+QCIlSsNsOlfLAGb8wEqDBwIRGG45UXjfO94sRBscF6lUvVeNFTcNvmETuKh+pqEKL1DbrRUYge5nIKS1Q1eAgUMmFkD/T6NqsnTjIE+ityDzrHZmGo4rLbUUIVy/GQBg+nuzFGy6FoA1tx0GvQC1veTk15Y1a3dJvmTyDLzRkjdDQpAIAcZhMYYXq/BOPwt5NUaa7NK0SY3rQddYKviJZL+lUEPTZyUhDluWMYaPd3kcspuEOay0thIHobNfnI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        argocd.argoproj.io/secret-type: repo-creds
      name: private-repo-creds
      namespace: argocd
# ArgoCD repo credentials that apply to the other repositories
# on a best-match basis.
---
{{- with .Values.github.repositories.dailyQuestions -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ .type }}
  url: {{ .url }}
{{- end -}}
---
{{- with .Values.github.repositories.personalProjectsHosting -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: {{ .type }}
  url: {{ .url }}
  path: {{ .path }}
{{- end -}}