apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sealedsecrets.namespace }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
{{- with .Values.sealedsecrets }}
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: {{ .targetRevision | quote }}
    helm:
      releaseName: sealed-secrets
  destination:
    server: {{ $.Values.argocd.destination.server }}
    namespace:  {{ .namespace }}
{{- end -}}
